### PR TITLE
Enhancement/Bug Fix

### PR DESCRIPTION
**Pull request by bsanders1979**
- Cache schema for prepared statement since query is immutable
- Convert "0000-00-00 00:00:00" to nil

### CODE REVIEW

**Comment by pilcrow** [comment]
@bsanders1979, thanks!  

Why do you `rescue` and default to an empty list when composing `@schema` ?  Is there a circumstance in which we plausibly expect to fail?

What undesired behavior is addressed by the `rescue ArgumentError` clause in the datetime_conv proc?  Do you have a plausible test case demonstrating?

**Comment by bsanders1979** [comment]
The @schema portion is a refactoring of the current code with the exception that it is only calculated on the first execution of the prepared statement

The rescue statement addresses issue 4
See:
https://github.com/RDBI/rdbi-driver-mysql/issues/6
https://github.com/RDBI/rdbi-driver-mysql/issues/4

**Comment by bsanders1979** [comment]
Just an FYI, I was looking at the documentation for the JDBC driver (http://dev.mysql.com/doc/refman/5.1/en/connector-j-reference-configuration-properties.html), and there is a metadataCacheSize parameter which seems to support the idea of storing the schema object as an instance variable.

**Comment by bsanders1979** [comment]
Is there anything preventing this pull request from being fulfilled?

**Pull request closed without merging**
